# stages:
#   - build
#   - deploy
#   - terraform_deploy


# services:
#   - docker:dind

# variables:
#   DOCKER_IMAGE_NAME: "$ACR_USERNAME.azurecr.io/$DOCKER_IMAGE"
#   DOCKER_IMAGE_TAG: "latest"

# build:
#   stage: build
#   image: docker:latest
#   script:
#     - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
#     - docker login $REGISTRY_NAME.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
#     - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
#     - echo "Application successfully deployed."
    
#   only:
#     - main # Run this job only for changes in the main branch

# deploy:
#   stage: deploy
#   image: ubuntu:latest
#   script:
#     - apt-get update -y
#     - apt-get install -y ansible
#     - ansible-playbook deploy_playbook.yml

#   only:
#     - main

stages:
  - terraform_prep
  - validate
  - plan
  - terraform_deploy

azure_login:
  stage: terraform_prep
  image:
    name: microsoft/azure-cli:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"

terraform_setup:
  stage: terraform_prep
  image: hashicorp/terraform:light
  script:
    - rm -rf .terraform
    - terraform --version
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan
  dependencies:
    - validate

  only:
    - main


