image: docker:latest

stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_IMAGE_NAME: "$DOCKER_HUB_USERNAME/weather-application"
  DOCKER_IMAGE_TAG: "latest"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - echo "Application successfully deployed."

  only:
    - main  # Run this job only for changes in the main branch
