stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_IMAGE_NAME: "$ACR_USERNAME.azurecr.io/$DOCKER_IMAGE"
  DOCKER_IMAGE_TAG: "latest"

build:
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker login $ACR_USERNAME.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - echo "Application successfully deployed."
    
  only:
    - main # Run this job only for changes in the main branch
