stages:
  - build

variables:
  DOCKER_IMAGE_NAME: "$DOCKER_HUB_USERNAME/weather-application"
  DOCKER_IMAGE_TAG: "latest"

before_script:
  - npm install  # If your project has dependencies, install them here

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD  # Log in to Docker Hub
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - main  # Run this job only for changes in the main branch
