stages:
  # - build
  # - deploy
  - terraform_deploy


# services:
#   - docker:dind

# variables:
#   DOCKER_IMAGE_NAME: "$ACR_USERNAME.azurecr.io/$DOCKER_IMAGE"
#   DOCKER_IMAGE_TAG: "latest"

# build:
#   stage: build
#   image: docker:latest
#   script:
#     - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
#     - docker login $REGISTRY_NAME.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
#     - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
#     - echo "Application successfully deployed."
    
#   only:
#     - main # Run this job only for changes in the main branch

# deploy:
#   stage: deploy
#   image: ubuntu:latest
#   script:
#     - apt-get update -y
#     - apt-get install -y ansible
#     - ansible-playbook deploy_playbook.yml

#   only:
#     - main

terraform_deploy:
  stage: terraform_deploy
  image: ubuntu:latest
  script:
    - apt-get update -y
    - apt-get install -y python3-pip
    - pip3 install --upgrade azure-cli
    - az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"

    - apt-get install -y gnupg
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
    - apt-get update -y
    - apt-get install -y terraform
    - terraform --version
    - terraform init
    - terraform plan
    - terraform validate 
    #- terraform apply -auto-approve
  only:
    - main
