# image: docker:latest

# stages:
#   - build

# services:
#   - docker:dind

# variables:
#   DOCKER_IMAGE_NAME: "$DOCKER_HUB_USERNAME/$DOCKER_IMAGE"
#   DOCKER_IMAGE_TAG: "latest"

# build:
#   stage: build
#   script:
#     - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
#     - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
#     - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
#     - echo "Application successfully deployed."

#   only:
#     - main  # Run this job only for changes in the main branch


# stages:
#   - deploy

# deploy:
#   stage: deploy
#   image: ubuntu:latest


#   script:
#     - apt-get update -qy
#     - apt-get install -y sshpass
#     - mkdir -p ~/.ssh
#     - echo "$AZURE_SSH_KEY" > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $AZURE_VM_USERNAME@$AZURE_VM_IP "sudo sh -c 'mkdir ajmerSingh'"
#     - echo "Application deployed to Azure VM."

#   only:
#     - main  # Run this job only for changes in the main branch

stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  variables:
    AZURE_VM_IP: "$AZURE_VM_IP"
    AZURE_VM_USERNAME: "$AZURE_VM_USERNAME"
    AZURE_SSH_KEY: "$AZURE_SSH_KEY"

  # before_script:
  #   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  #   - mkdir -p ~/.ssh
  #   - eval $(ssh-agent -s)
  #   - echo "$AZURE_SSH_KEY" > ~/.ssh/id_rsa
  #   - chmod 600 ~/.ssh/id_rsa
  #   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$AZURE_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no $AZURE_VM_USERNAME@$AZURE_VM_IP 'sudo mkdir /var/www/html/ajmerSingh'



    - ssh-add ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $AZURE_VM_USERNAME@$AZURE_VM_IP 'sudo mkdir /var/www/html/ajmerSingh'

  only:
    - main  # Run this job only for changes in the main branch

