---
- name: Deploy to Azure Container Instances
  hosts: localhost
  become: yes

  tasks:
    - name: Login to Azure Container Registry
      shell: az acr login --name $REGISTRY_NAME --username "{{ ACR_USERNAME }}" --password "{{ ACR_PASSWORD }}"
      environment:
        ACR_USERNAME: "{{ ACR_USERNAME }}"
        ACR_PASSWORD: "{{ACR_PASSWORD }}"

    - name: Pull Docker image from Azure Container Registry
      shell: docker pull $ACR_USERNAME.azurecr.io/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG

    - name: Create Azure Container Instance
      azure_rm_containerinstance:
        resource_group: gitlab
        name: abc
        image: $ACR_USERNAME.azurecr.io/$DOCKER_IMAGE:$DOCKER_IMAGE_TAG
        dns_name_label: weather
        cpu: 1
        memory_in_gb: 1
        os_type: Linux
        state: present
