apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2  # Adjust based on your scaling requirements
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-container
          image: gitlabansible.azurecr.io/weather_application:latest
          ports:
            - containerPort: 3000  # Adjust based on your application's port
      imagePullSecrets:
        - name: mycredentials  # Reference to the secret

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80  # Adjust based on the service port you want to expose
      targetPort: 3000  # Should match the containerPort in Deployment
  type: LoadBalancer 
